import Head from "next/head";
import Navbar from "../../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="text-text-100 bg-bg-100">Modern portfolio project</main>
    </>
  );
}
